### ISSUE TITLE
Menus can't be used with controller

### ISSUE THREAD

**Issue by BenBohannon** [Ixrec/OuterWildsArchipelagoRandomizer#18]
When starting a new randomized expedition, the connection info menu for host and port appears but doesn't respond to controller inputs. Pressing start or B button doesn't do anything.

Keyboard also doesn't work. Only mouse works.

Using:
xbox one wireless controller
Latest Outer Wilds version as of today (July 8th 2024)
Outer Wilds Mod Manager 0.14.2
Outer Wilds Archipelago Randomizer 0.2.3
Menu Framework 5.0.0

Possibly related: In the settings menu, the "Mods" group under the Mods tab (to the right of OWML) also doesn't respond to anything but the mouse. All other menus respond to mouse and keyboard as expected.

**Comment by Ixrec** [comment]
Yeah, I'm pretty sure this is an OWML issue since my code doesn't handle any of the input events for these popups, and as you pointed out it also affects the "Mods" menu that exists for all other mods.
