### ISSUE TITLE
Minor Bug:  Skipping nap traps

### ISSUE THREAD

**Issue by Kriellya** [Ixrec/OuterWildsArchipelagoRandomizer#33]
It seems to be possible to skip the nap trap by sleeping as the nap trap comes in.  You can wake up from the campfire nap after the nap trap has started and gain full control, including the ability to interact with dialogues.

I need to figure out how to do some further testing to determine how easy this is to actually trigger, and if this has a different interaction with dream naps.

Specific steps I did that caused it initially:
1. Get to Feldspar's camp, shipless (i.e; do not have the launch codes)
2. Get sent a nap trap while standing next to his campfire
3. Decide now is an excellent time for a marshmallow, thanks to generous application of lithobraking, and misclick to nap instead.
4. Reflexively cancel the campfire nap, because that's how often you accidentally nap instead of roasting a marshmallow

Effect: You're now awake with full control, with the text "nap trap in progress" displaying on screen as if you're in a nap trap, and very confused.  A minute on the clock later, the game will play the "waking up" scene, regardless of what you're doing (it played while I was talking with Feldspar, which was kinda hilarious)

Have not attempted to replicate under other conditions yet, but based on having done this completely on accident, I doubt most of them are.  Just including them here in case they *are* somehow relevant (no launch codes in particular could be a very weird state)

**Comment by thastegartivelis** [comment]
Um... spoilers I guess?

I was able to do something similar by sleeping at a fire in The Stranger during the countdown, which let me walk around the Dream World with the "nap trap in progress" text on the screen. I was not woken up when the trap ended, though.

**Comment by Ixrec** [comment]
Interesting. This might be one of those corner cases that's not worth fixing; historically, trying to make nap traps unskippable has tended to cause the opposite problem of sleep paralysis / being softlocked when the trap ends.

**Comment by Kriellya** [comment]
Reasonable, given the relatively low impact 🤷‍♀️
If I find a way to "skip" it that ends up softlocking the loop, I'll let you know

**Comment by Ixrec** [comment]
closing as "won't do" for now, given the risks of reintroducing nap trap softlocks outweigh the benefit of preventing these trap skips (if it even is a benefit; like "sleepwalking" I suspect it's more fun to simply leave it in)
