### ISSUE TITLE
[Request] Randomizer Suit Log

### ISSUE THREAD

**Issue by pakoito** [Ixrec/OuterWildsArchipelagoRandomizer#35]
Hi! My request is to embed a copy of the Suit Log mod, specialized for the Randomizer. Specially when learning, going back and forth to the ship to remember which note is the one that triggers a check, or what item is required for a check, is time-consuming.

**Comment by Pikrass** [comment]
I've started working on this. It's pretty easy to implement, the mod's custom ship logs can just be reused as is.

The only bug I seem to have is that images don't show in the checklist until the ship log has been opened. I'll submit a PR after I've looked into this.

**Comment by pakoito** [comment]
u da GOAT

**Comment by Ixrec** [comment]
Closed by #38
