### ISSUE TITLE
Deathlink causes a crash while in map

### ISSUE THREAD

**Issue by Madeline-Code-Cache** [Ixrec/OuterWildsArchipelagoRandomizer#36]
Deathlink causes a crash when you are in the solar system map. Current setting for deathlink is all deaths and the crash gets triggered when you die in the map because of a death in another client (like Mario 64 in this case).

**Comment by Ixrec** [comment]
After manually triggering several death links on the map screen, I haven't received a single crash.

Most likely, this is the familiar "end of loop crash" that no one can get to happen consistently. Maybe later I'll write up an issue on what little we know about it, but all the evidence we have points to the randomizer not being the cause and not being able to fix or work around it.
